name: Bug Report
description: Create a report to help us fix a bug in BatBrowser
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment Info
      description: OS version, Electron version, BatBrowser version.
      placeholder: Windows 11, BatBrowser v2.0.0
